name: BSC
on:
  push:
    branches: [main]
    paths:
      - "contracts/**"
      - "test/bsc/**"
  pull_request:
    branches: [main]
    paths:
      - "contracts/**"
      - "test/bsc/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn compile
        env:
          JSON_RPC_URL: ${{ secrets.BSC_RPC_URL }}
      - run: yarn test test/bsc/*.ts
        env:
          JSON_RPC_URL: ${{ secrets.BSC_RPC_URL }}